parameters:
#    gestion_emplois.example.class: Gestion\EmploisBundle\Example

services:
#    gestion_emplois.example:
#        class: %gestion_emplois.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
