<?php

namespace Gestion\OffreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmploieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmploieRepository extends EntityRepository
{
}
