<?php

namespace User\PartageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{
         public function getDocumentAvecMotCles()
{
             $user = $this->get('security.context')->getToken()->getUser();
  $qb = $this->createQueryBuilder('d')
             ->join('d.motCles', 'mc')
          ->where('d.user',$user)
             ->addSelect('mc');
 
  return $qb->getQuery()
            ->getResult();
}
}
