infoNouvelle:
    pattern:  /
    defaults: { _controller: UserNewsBundle:InfoNouvelle:affichListeNouvelle }
infoNouvelle_show:
    pattern:  /show/{id}
    defaults: { _controller: UserNewsBundle:InfoNouvelle:show }

