<?php

namespace Proxies\__CG__\Gestion\EmploisBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Classe extends \Gestion\EmploisBundle\Entity\Classe implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setCode($code)
    {
        $this->__load();
        return parent::setCode($code);
    }

    public function getCode()
    {
        $this->__load();
        return parent::getCode();
    }

    public function setFormation(\Gestion\EmploisBundle\Entity\Formation $formation = NULL)
    {
        $this->__load();
        return parent::setFormation($formation);
    }

    public function getFormation()
    {
        $this->__load();
        return parent::getFormation();
    }

    public function setDiplome(\Gestion\EmploisBundle\Entity\Diplome $diplome = NULL)
    {
        $this->__load();
        return parent::setDiplome($diplome);
    }

    public function getDiplome()
    {
        $this->__load();
        return parent::getDiplome();
    }

    public function setNbGroupe($nbGroupe)
    {
        $this->__load();
        return parent::setNbGroupe($nbGroupe);
    }

    public function getNbGroupe()
    {
        $this->__load();
        return parent::getNbGroupe();
    }

    public function setNiveau($niveau)
    {
        $this->__load();
        return parent::setNiveau($niveau);
    }

    public function getNiveau()
    {
        $this->__load();
        return parent::getNiveau();
    }

    public function addAffectation(\Gestion\EmploisBundle\Entity\AffectationPlan $affectations)
    {
        $this->__load();
        return parent::addAffectation($affectations);
    }

    public function removeAffectation(\Gestion\EmploisBundle\Entity\AffectationPlan $affectations)
    {
        $this->__load();
        return parent::removeAffectation($affectations);
    }

    public function getAffectations()
    {
        $this->__load();
        return parent::getAffectations();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function addEmploi(\Gestion\EmploisBundle\Entity\Emploi $emplois)
    {
        $this->__load();
        return parent::addEmploi($emplois);
    }

    public function removeEmploi(\Gestion\EmploisBundle\Entity\Emploi $emplois)
    {
        $this->__load();
        return parent::removeEmploi($emplois);
    }

    public function getEmplois()
    {
        $this->__load();
        return parent::getEmplois();
    }

    public function addEtudiant(\Gestion\UserBundle\Entity\Etudiant $etudiants)
    {
        $this->__load();
        return parent::addEtudiant($etudiants);
    }

    public function removeEtudiant(\Gestion\UserBundle\Entity\Etudiant $etudiants)
    {
        $this->__load();
        return parent::removeEtudiant($etudiants);
    }

    public function getEtudiants()
    {
        $this->__load();
        return parent::getEtudiants();
    }

    public function addAffectationEtudiant(\Gestion\EmploisBundle\Entity\AffectationEtudiant $affectationEtudiants)
    {
        $this->__load();
        return parent::addAffectationEtudiant($affectationEtudiants);
    }

    public function removeAffectationEtudiant(\Gestion\EmploisBundle\Entity\AffectationEtudiant $affectationEtudiants)
    {
        $this->__load();
        return parent::removeAffectationEtudiant($affectationEtudiants);
    }

    public function getAffectationEtudiants()
    {
        $this->__load();
        return parent::getAffectationEtudiants();
    }

    public function addAbsence(\Gestion\AbsenceNoteBundle\Entity\Absence $absences)
    {
        $this->__load();
        return parent::addAbsence($absences);
    }

    public function removeAbsence(\Gestion\AbsenceNoteBundle\Entity\Absence $absences)
    {
        $this->__load();
        return parent::removeAbsence($absences);
    }

    public function getAbsences()
    {
        $this->__load();
        return parent::getAbsences();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'code', 'nbGroupe', 'niveau', 'formation', 'diplome', 'affectations', 'absences', 'affectationEtudiants', 'emplois', 'etudiants');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}