Message:
    type: entity
    table: message
    fields:
        idMessage:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_Message
            generator:
                strategy: IDENTITY
        destination:
            type: string
            length: 255
            fixed: false
            nullable: false
        subject:
            type: string
            length: 255
            fixed: false
            nullable: false
        corps:
            type: text
            nullable: false
        pieceJointe:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: piece_jointe
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
