<?php

namespace Gestion\EmploisBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AffectationEtudiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffectationEtudiantRepository extends EntityRepository
{
}
