<?php

namespace Gestion\EmploisBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlanEtudeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanEtudeRepository extends EntityRepository
{
}
