<?php

namespace Gestion\EmploisBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfilClasseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilClasseRepository extends EntityRepository
{
}
