<?php

namespace Gestion\CalendrierBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EvenementUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementUserRepository extends EntityRepository
{
}
