parameters:
#    question_reponse_question_reponse.example.class: Question\Reponse\QuestionReponseBundle\Example

services:
#    question_reponse_question_reponse.example:
#        class: %question_reponse_question_reponse.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    nbrenotif:
        class: Question\Reponse\QuestionReponseBundle\nbre\nbrenotif
        arguments: [ '@doctrine.orm.entity_manager','@service_container','@question_repository' ]
    question_repository:
        class: Question\Reponse\QuestionReponseBundle\Entity\QuestionRepository
        arguments: [QuestionReponseQuestionReponseBundle:Question]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
    nbrereponse:
        class: Question\Reponse\QuestionReponseBundle\nbre\nbrereponse
        arguments: [ '@doctrine.orm.entity_manager','@service_container','@reponse_repository' ]
    reponse_repository:
        class: Question\Reponse\QuestionReponseBundle\Entity\ReponseRepository
        arguments: [QuestionReponseQuestionReponseBundle:Reponse]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        