parameters:
#    user_news.example.class: User\NewsBundle\Example

services:
#    user_news.example:
#        class: %user_news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
